

from .config import (
    AZURE_MISTRAL_LARGE_API, AZURE_MISTRAL_SMALL_API, AZURE_DEEPSEEK_API,
    AZURE_MISTRAL_LARGE_INFERENCE_KEY, AZURE_MISTRAL_SMALL_INFERENCE_KEY,
    AZURE_DEEPSEEK_INFERENCE_KEY, AZURE_OPENAI_API_BASE, AZURE_OPENAI_API_KEY,
    AZURE_OPENAI_API_GPT_4o_MINI, AZURE_OPENAI_API_GPT_4o,
    OPENROUTER_API_KEY, OPENAI_API_KEY, OPENAI_MODEL,
    ANTHROPIC_API_KEY, AZURE_OPENAI_API_GPT41_BASE,
    AZURE_OPENAI_API_GPT_41, AZURE_OPENAI_API_GPT_41_KEY
)


class LLMProvider:
    AZURE_MISTRAL_SMALL = "azure_mistral_small"
    AZURE_MISTRAL_LARGE = "azure_mistral_large"
    AZURE_OPENAI_GPT_4o = "azure_openai_gpt_4o"
    AZURE_OPENAI_GPT_4o_MINI = "azure_openai_gpt_4o_mini"
    AZURE_OPENAI_GPT_41 = "azure_openai_gpt_41"
    AZURE_DEEPSEEK = "azure_deepseek"
    OPENAI = "openai"
    OPENROUTER = "openrouter"
    ANTHROPIC = "anthropic"

# Azure LLM Mapping
LLM_2_ENDPOINT = {
    LLMProvider.OPENAI: "n/a",
    LLMProvider.OPENROUTER: "https://openrouter.ai/api/v1",
    LLMProvider.ANTHROPIC: "n/a",
    LLMProvider.AZURE_MISTRAL_LARGE: AZURE_MISTRAL_LARGE_API,
    LLMProvider.AZURE_MISTRAL_SMALL: AZURE_MISTRAL_SMALL_API,
    LLMProvider.AZURE_DEEPSEEK: AZURE_DEEPSEEK_API,
    LLMProvider.AZURE_OPENAI_GPT_4o: AZURE_OPENAI_API_BASE,
    LLMProvider.AZURE_OPENAI_GPT_4o_MINI: AZURE_OPENAI_API_BASE,
    LLMProvider.AZURE_OPENAI_GPT_41: AZURE_OPENAI_API_GPT41_BASE,
    }

LLM_2_INFERENCE_KEY = {
    LLMProvider.AZURE_MISTRAL_LARGE: AZURE_MISTRAL_LARGE_INFERENCE_KEY,
    LLMProvider.AZURE_MISTRAL_SMALL: AZURE_MISTRAL_SMALL_INFERENCE_KEY,
    LLMProvider.AZURE_DEEPSEEK: AZURE_DEEPSEEK_INFERENCE_KEY,
    LLMProvider.AZURE_OPENAI_GPT_4o: AZURE_OPENAI_API_KEY,
    LLMProvider.AZURE_OPENAI_GPT_4o_MINI: AZURE_OPENAI_API_KEY,
    LLMProvider.AZURE_OPENAI_GPT_41: AZURE_OPENAI_API_GPT_41_KEY,
    LLMProvider.OPENAI: OPENAI_API_KEY,
    LLMProvider.OPENROUTER: OPENROUTER_API_KEY,
    LLMProvider.ANTHROPIC: ANTHROPIC_API_KEY
    }

LLM_2_MODEL = {
    LLMProvider.AZURE_OPENAI_GPT_4o: AZURE_OPENAI_API_GPT_4o,
    LLMProvider.AZURE_OPENAI_GPT_4o_MINI: AZURE_OPENAI_API_GPT_4o_MINI,
    LLMProvider.AZURE_OPENAI_GPT_41: AZURE_OPENAI_API_GPT_41,
    LLMProvider.AZURE_MISTRAL_LARGE: "n/a",
    LLMProvider.AZURE_MISTRAL_SMALL: "n/a",
    LLMProvider.AZURE_DEEPSEEK: "n/a",
    LLMProvider.OPENAI: OPENAI_MODEL,
    LLMProvider.OPENROUTER: "",
    LLMProvider.ANTHROPIC: "",
    }